src/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.urls import path

import sitemap

admin.autodiscover()

urlpatterns = [
    path('admind/', admin.site.urls),
    url(r'^dynamic_sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps}),
    url(r'^', include('discounts.urls')),
    url(r'^', include('mountains.urls')),
    url(r'^', include('movies.urls')),
    url(r'^', include('core.urls')),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/mountains/models.py
# coding: utf-8
from django.db import models
from django.urls import reverse
from yafotki.fields import YFField


class Region(models.Model):
    """ Регион """
    title = models.CharField(max_length=250, verbose_name='Название')
    order = models.PositiveIntegerField(verbose_name='Порядок')
    meta_description = models.TextField(verbose_name='Description', help_text='meta-description',
                                        null=True, blank=True, default=None)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('region', args=[self.id])

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'
        ordering = ['order']


class District(models.Model):
    """ Область """
    title = models.CharField(max_length=250, verbose_name='Название')

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('district', args=[self.id])

    class Meta:
        verbose_name = 'Область'
        verbose_name_plural = 'Области'


class Mountain(models.Model):
    slug = models.CharField(max_length=250, null=True, blank=True, unique=True, verbose_name='Код горы')
    title = models.CharField(max_length=250, null=True, blank=True, verbose_name='Название')
    content = models.TextField(null=True, blank=True, verbose_name='Содержание элемента')
    status = models.CharField(max_length=50, null=True, blank=True, verbose_name='Статус')

    address = models.CharField(max_length=200, null=True, blank=True, verbose_name='Адрес')
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='Область')
    has_ratrack = models.BooleanField(default=False, verbose_name='Есть ратрак')
    hidden = models.BooleanField(default=False, verbose_name='Скрытый')
    image = YFField(upload_to='gladerru', null=True, blank=True, verbose_name='Схема трасс', default=None)
    lifts = models.TextField(null=True, blank=True, verbose_name='Подъемники')
    latitude = models.CharField(max_length=20, null=True, blank=True, verbose_name='Широта')
    longitude = models.CharField(max_length=20, null=True, blank=True, verbose_name='Долгота')
    longest = models.CharField(max_length=50, null=True, blank=True, verbose_name='Самая длинная трасса')
    nightwork = models.TextField(null=True, blank=True, verbose_name='Ночная работа', help_text='До скольки')
    oldschool = models.BooleanField(default=False, verbose_name='Олдскул')
    overfall = models.CharField(max_length=50, null=True, blank=True, verbose_name='Перепад высот')
    pistelength = models.CharField(max_length=50, null=True, blank=True, verbose_name='Общая длина трасс')
    pistes = models.CharField(max_length=50, null=True, blank=True, verbose_name='Кол-во трасс')
    prices = models.TextField(null=True, blank=True, verbose_name='Цены')
    rating = models.FloatField(default=0.0, verbose_name='Рейтинг')
    region = models.ForeignKey(Region, on_delete=models.DO_NOTHING, verbose_name='Регион')
    service = models.TextField(null=True, blank=True, verbose_name='Услуги')
    snowpark = models.TextField(null=True, blank=True, verbose_name='Сноупарк')
    tel = models.CharField(max_length=250, null=True, blank=True, verbose_name='Телефоны')
    url = models.URLField(max_length=250, null=True, blank=True, verbose_name='URL')
    webcam = models.URLField(max_length=250, null=True, blank=True, verbose_name='Web камера')
    work_time = models.TextField(null=True, blank=True, verbose_name='Время работы')
    email = models.EmailField(null=True, blank=True, verbose_name='Email')
    interactive_map = models.TextField(verbose_name='Интеракт. карта', null=True, blank=True, default=None)

    newbie = models.BooleanField(default=False, verbose_name='Есть учебный склон')
    parking = models.BooleanField(default=False, verbose_name='Есть платная стоянка')
    rental = models.BooleanField(default=False, verbose_name='Есть прокат оборудования')
    room = models.BooleanField(default=False, verbose_name='Комната для переодевания')
    safe = models.BooleanField(default=False, verbose_name='Есть камера хранения')
    has_service = models.BooleanField(default=False, verbose_name='Есть мастерская/сервис')
    cafe = models.BooleanField(default=False, verbose_name='Есть кафе')
    hotel = models.TextField(null=True, blank=True, verbose_name='Гостиница')
    has_light = models.BooleanField(default=False, verbose_name='Есть освещение трасс')
    has_show = models.BooleanField(default=False, verbose_name='Искусственный снег')

    check_date = models.DateField(null=True, blank=True, verbose_name='Дата обработки')
    proof_url = models.TextField(null=True, blank=True, verbose_name='Источник данных')
    meta_description = models.TextField(verbose_name='Description', help_text='meta-description',
                                        null=True, blank=True, default=None)

    def get_absolute_url(self):
        return reverse('mountain', args=[self.slug])

    def __unicode__(self):
        return self.title

    @property
    def uid(self):
        return '%s_%s' % (self.__class__.__name__.lower(), self.id)

    class Meta:
        verbose_name = 'Гора'
        verbose_name_plural = 'Горы'


class MountainPhoto(models.Model):
    mountain = models.ForeignKey(Mountain, on_delete=models.DO_NOTHING, verbose_name='Гора')
    image = YFField(upload_to='gladerru', verbose_name='Картинка')

    class Meta:
        verbose_name = 'Фото горы'
        verbose_name_plural = 'Фото гор'

src/templates/3/admin/child_form.html
<form action="/create/child" method="post">
    <table>
        {{ form }}
        <tr><td colspan="2" align="right"><input type="submit" value="Добавить"></td></tr>
    </table>
</form>

src/templates/3/admin/new_district_form.html
{% if is_mountain %}
<form action="/create/district" method="post">
    <strong>Область</strong>:
    <select name="mm"><option value="">выберите</option>{% for mm in districts %}<option value="{{ mm.id }}">{{ mm.title }}</option>{% endfor %}</select><br /> 
    или новая <input type="text" name="district" id="id_district" size="30"/><br />
    <input type="submit" value="Добавить">
    <input type="hidden" name="object_id" value="{{ object_id }}">
</form>
{% endif %}

src/templates/3/admin/new_moviemaker_form.html
{% if is_movie %}
<form action="/create/moviemaker" method="post">
    <strong>Студия</strong>:
    <select name="mm"><option value="">выберите</option>{% for mm in moviemakers %}<option value="{{ mm.id }}">{{ mm.title }}</option>{% endfor %}</select><br /> 
    или новая <input type="text" name="moviemaker" id="id_moviemaker" size="30"/><br />
    <input type="submit" value="Добавить">
    <input type="hidden" name="object_id" value="{{ object_id }}">
</form>
{% endif %}

src/templates/3/admin/new_rider_form.html
{% if is_movie %}
<form action="/create/rider" method="post">
    <strong>Райдер</strong>: <input type="text" name="rider" id="id_rider" />
    <input type="submit" value="Добавить">
    <input type="hidden" name="object_id" value="{{ object_id }}">
</form>
{% endif %}

src/templates/3/admin/observe_404.html
{% extends "base.html" %}

{% block content %}
<ul>
	{% for link in links %}
		<li style="padding: 4px; background-color: #eee; margin-bottom: 3px; border: 1px solid gray;">
			<a href="" onclick="$('#block_{{ link.0 }}').toggleClass('g-hidden'); return false;">+</a> {{ link.1 }} ({{ links.3|length }})</li>
		<div class="g-hidden" id="block_{{ link.0 }}" style="padding: 3px 0px 10px 20px;">
			{% for rec in link.3 %}
				{{ rec.dt }} {{ rec.referrer }} {{ rec.ua }}<br>
			{% endfor %}
		</div>
	{% endfor %}
</ul>
{% endblock %}

src/templates/3/admin/relation_form.html
<form action="/create/relation" method="post">
    <table>
        {{ form }}
        <tr><td colspan="2" align="right"><input type="submit" value="Добавить"></td></tr>
    </table>
</form>

src/templates/3/admin/relations.html
<ul>
{% for r in relations %}
    <li><a href="/admin/core/item/{{ r.item_a.id }}/">{{ r.item_a }}</a> -> <a href="/admin/core/item/{{ r.item_b.id }}/">{{ r.item_b }}</a> (<a href="/admin/core/relation/{{ r.id }}/">{{ r.rel_type.name }}</a>)</li>
{% endfor %}
</ul> 
    

src/templates/3/admin/tag_replace_form.html
<form action="/create/tag_replace" method="post">
    <strong>Замена тега</strong>:
    <input type="text" name="new_tag" id="id_new_tag" size="50"/><br />
    <input type="submit" value="Добавить">
    <input type="hidden" name="object_id" value="{{ object_id }}">
</form>

src/templates/3/admin/timing_report.html
{% extends "base.html" %}

{% block content %}

<style>
	td,th { padding-right: 5px; }
</style>

<table>
	<tr>
		<th>Урл</th>
		<th>Среднее время</th>
		<th>Минимальное</th>
		<th>Максимальное</th>
		<th>Общее количество</th>
	</tr>
		
	{% for link in links %}
		<tr>
			<td><a href="" onclick="$('#block_{{ link.id }}').toggleClass('g-hidden'); return false;">+</a>
				<a href="//glader.ru{{ link.url }}">{{ link.url }}</a></td>
			<td>{{ link.average }}</td>
			<td>{{ link.min }}</td>
			<td>{{ link.max }}</td>
			<td>{{ link.amount }}</td>
		</tr>
		<tr class="g-hidden" id="block_{{ link.id }}">
			<td colspan="5" style="padding-left: 30px;">
				{% for rec in link.all %}
					{{ rec }}<br>
				{% endfor %}
			</td>
		</tr>
	{% endfor %}
</table>

{% endblock %}